server:
  port: 10010
spring:
  application:
    name: msns-gateway
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
zuul:
  prefix: /api
  routes:
    dynamic-service: /dynamic/**
    music-service: /music/**
    user-service: /user/**
    admin-service: /admin/**
    comment-service: /comment/**
    favor-service: /favor/**
    like-service: /like/**
  ignored-patterns: /upload/**
  ignored-services:
    - upload-service